### ISSUE TITLE
输入型组件切换为选择型组件后，添加选项报错

### ISSUE THREAD

**Issue by yuni-bg** [JakHuang/form-generator#191]
![image](https://github.com/JakHuang/form-generator/assets/53655494/bc2c38cd-5cd2-4497-8479-e10b96e373ef)

vue.min.js:6 TypeError: Cannot read properties of undefined (reading 'push')
    at a.addSelectItem (index.10eebaa4.js:1:113226)
    at He (vue.min.js:6:11384)
    at a.n (vue.min.js:6:13168)
    at He (vue.min.js:6:11384)
    at e.$emit (vue.min.js:6:34373)
    at a.handleClick (index.js:1:125167)
    at He (vue.min.js:6:11384)
    at HTMLButtonElement.n (vue.min.js:6:13168)
    at Yr.o._wrapper (vue.min.js:6:48505)
Ue @ vue.min.js:6
Be @ vue.min.js:6
Re @ vue.min.js:6
He @ vue.min.js:6
n @ vue.min.js:6
He @ vue.min.js:6
e.$emit @ vue.min.js:6
handleClick @ index.js:1
He @ vue.min.js:6
n @ vue.min.js:6
Yr.o._wrapper @ vue.min.js:6

**Comment by maomaojiujiu** [comment]
请问下你这边是怎么跑起来这个项目的，为啥我一运行npm run dev就嘎嘎报错啊，不支持vue3吗
